#!/bin/bash

node ~/dev/git/localhost/server.js &
setxkbmap -option
setxkbmap -layout us,ru
dunst -config ~/.config/dunst/gruvbox.conf &
bash ~/scripts/battery_alert.sh &
bash ~/scripts/player.sh>/dev/null 2>/dev/null &
picom &
xrdb -merge .Xresources &
#slstatus &
pypy3 /home/virashu/dev/git/pystatus/status.py &
sh ~/.fehbg &

while true ; do
    dwm >~/.logs/dwm.log 2>&1 || break
done 

